#!/usr/bin/env bash


CC=$1; shift
[ -z "$CC" ] && {
  CC=cc
}


if echo -e "int main(){}" | ${CC} -x c -fprofile-generate - -o /dev/null 2>/dev/null; then
  if ! [ -z "$(${CC} --version | head -1 | grep 'clang')" ]; then
    echo clang
  else
    echo gcc
  fi
else
  echo disabled
fi
