#!/usr/bin/env bash


CXX=$1; shift
[ -z "${CXX}" ] && {
  CXX=c++
}

tmpfilename="/tmp/test-jemalloc-${RANDOM}"
printf "#include<stdlib.h>\n#include<stdio.h>\n#include<dlfcn.h>\nextern \"C\"{int mallctl(const char *name,void *oldp,size_t *oldlenp,void *newp,size_t newlen) __attribute__((weak));} bool check_jemalloc(){return (mallctl!=nullptr);}int main(){return check_jemalloc()?1:0;}" | ${CXX} -x c++ - -o "$tmpfilename" 2>/dev/null
$tmpfilename
result=$?
rm -f "$tmpfilename"

#echo "result $result"

if test $result -eq 1; then
  echo "builtin"
elif printf "#include <jemalloc/jemalloc.h>\nint main(){malloc;}" | ${CXX} -x c++ -ljemalloc - -o /dev/null 2>/dev/null; then
  echo "external"
else
  echo "disabled"
fi

