#!/usr/bin/env bash


CC=$1; shift
[ -z "${CC}" ] && {
  CC=cc
}

if echo -e '
#include <stdlib.h>
int main(){printf("%d", (int)arc4random());}' \
 | ${CC} -x c - -o /dev/null 2>/dev/null; then
  echo "bsd"
else
  echo "disabled"
fi
