#!/usr/bin/env bash

CXX="$1"; shift
[ -z "${CXX}" ] && {
  CXX=c++
}

# https://wiki.musl-libc.org/open-issues
if ! echo -e "#include <features.h>
#if !defined(__GLIBC__) && !defined(__APPLE__)
#error no glibc
#endif
int main(){}" | "${CXX}" -x c++ - -o /dev/null 2>/dev/null; then
  echo "disabled"
  exit 0
fi

# https://man.openbsd.org/clang-local.1
if test "$(uname -s)" = 'OpenBSD'; then
  echo "minimal"
  exit 0
fi

# Check if static sanitizer libraries are available (GCC only)
if echo "int main(){}" | "${CXX}" -x c++ - -fsanitize=address -fsanitize=undefined -static-libasan -static-libubsan -o /dev/null 2>/dev/null; then
  echo "enabled-static"
else
  echo "enabled-dynamic"
fi
