#!/usr/bin/env bash


CC=$1; shift
[ -z "${CC}" ] && {
  CC=cc
}

# musl doesn't support -pg flag (gcrt1.o not found)
if printf "int main(){}" | ${CC} -x c -pg - -o /dev/null 2>/dev/null; then
  echo "enabled"
else
  echo "disabled"
fi
