#!/bin/bash


[ -e 'm42.h' ]   || wget https://raw.githubusercontent.com/sinandredemption/M42/master/m42.h -O m42.h
[ -e 'm42.cpp' ] || wget https://raw.githubusercontent.com/sinandredemption/M42/master/m42.cpp -O m42.cpp
